//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserSecretsManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserSecretsManager.Resources.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating backup for project {0}: {1}.
        /// </summary>
        internal static string BackupCreationError {
            get {
                return ResourceManager.GetString("BackupCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup file for project {0} was not found..
        /// </summary>
        internal static string BackupFileNotFound {
            get {
                return ResourceManager.GetString("BackupFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening file: {0}.
        /// </summary>
        internal static string FileOpeningError {
            get {
                return ResourceManager.GetString("FileOpeningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secrets file for project {0} was not found..
        /// </summary>
        internal static string ProjectSecretsFileNotFound {
            get {
                return ResourceManager.GetString("ProjectSecretsFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error restoring secrets for project {0}: {1}.
        /// </summary>
        internal static string RestoreError {
            get {
                return ResourceManager.GetString("RestoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when writing to user secrets file {0}: {1}.
        /// </summary>
        internal static string SecretsFileWritingError {
            get {
                return ResourceManager.GetString("SecretsFileWritingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section was not found in the list of all sections..
        /// </summary>
        internal static string SectionNotFound {
            get {
                return ResourceManager.GetString("SectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Secrets folder was not found..
        /// </summary>
        internal static string UserSecretsFolderNotFound {
            get {
                return ResourceManager.GetString("UserSecretsFolderNotFound", resourceCulture);
            }
        }
    }
}
